export const DEMO_DATA = {
  incident: {
    code: "INC-2026-0847",
    title_th: "น้ำท่วม + MCI ตลิ่งชัน",
    title_en: "Flood + MCI Taling Chan",
    type: "Flood / Mass Casualty",
    response_level: "REGIONAL",
    command_mode: "JOINT",
    lead_org: "Bangkok EOC + Royal Thai Army Medical",
    status: "active",
    op_period: "OP-3",
    iap_version: "v2.1",
    started: "T+04:12",
    location: { lat: 13.7775, lng: 100.4582 },
  },
  drill: {
    code: "DRL-2026-FLOOD-MCI-001",
    title_th: "การฝึกร่วม น้ำท่วม + MCI ปี 2569",
    title_en: "Joint Hybrid Drill — Flood + MCI 2026",
    type: "full_scale",
    teams: 20,
    casualties_total: 240,
    sim_clock: "T+01:35",
    sim_status: "live",
  },
  metrics_op: [
    { label: "ผู้ป่วยที่ปฏิบัติการ", value: 82, unit: "", footer: "P1 8 · P2 24 · P3 47 · ⬛ 3", tone: "" },
    { label: "ทีมที่ส่ง", value: 14, unit: "/ 18", footer: "กำลังเดินทาง 4 · ถึงที่เกิดเหตุ 10", tone: "" },
    { label: "สถานะ รพ.", value: 2, unit: "เบี่ยง", tone: "warn", footer: "ศิริราช (R2) · CoE พมก." },
    { label: "ด่านความปลอดภัย", value: 1, unit: "วิกฤต", tone: "critical", footer: "ด่านขีดความสามารถ รพ. ไม่ผ่าน" },
    { label: "ระดับตอบสนอง", value: "ระดับภูมิภาค", footer: "ยกระดับ T+03:40", tone: "warn" },
    { label: "ความครบถ้วน COP", value: 87, unit: "%", footer: "12 จาก 14 จุด รายงานแล้ว", tone: "ok" },
  ],
  metrics_drill: [
    { label: "เวลาฝึก (Sim Clock)", value: "T+01:35", footer: "สด · ผู้ควบคุม 4 คน", tone: "" },
    { label: "ทีมที่พร้อม", value: 18, unit: "/ 20", footer: "รอ Check-in 2 ทีม" },
    { label: "ผู้ประสบภัยจำลอง", value: 162, unit: "/ 240", footer: "รอค้นพบ 78 ราย" },
    { label: "Inject ที่ส่งแล้ว", value: 7, unit: "/ 24", footer: "ถัดไป: T+01:40 P1 Surge", tone: "warn" },
    { label: "ละเมิดความปลอดภัย", value: 3, unit: "รายการ", footer: "วิกฤตทั้งหมดถูกทบทวนแล้ว", tone: "critical" },
    { label: "ผู้ประเมิน", value: 8, unit: "ออนไลน์", footer: "บันทึกการสังเกต 126 รายการ", tone: "ok" },
  ],
  sites: [
    { id: "SITE-A", name: "ตลิ่งชัน หมู่บ้าน A", name_en: "Taling Chan Village A", x: 28, y: 38, type: "incident", hazard: "Flooding", patients: 34, zone: "warm" },
    { id: "SITE-B", name: "โรงเรียนวัดไก่เตี้ย", name_en: "Wat Kai Tia School", x: 42, y: 56, type: "incident", hazard: "Trapped elders", patients: 18, zone: "warm" },
    { id: "CCP-1", name: "จุดรวมผู้ป่วย CCP-1", name_en: "Casualty Collection Pt 1", x: 36, y: 48, type: "ccp", patients: 22 },
    { id: "LZ-1", name: "LZ ลานพระอาทิตย์", name_en: "LZ Phra Athit", x: 58, y: 35, type: "lz", safety: "passed" },
    { id: "FAC-R2-SIR", name: "Role 2 ศิริราช", name_en: "Role 2 Siriraj", x: 65, y: 52, type: "facility", role: "Role 2", status: "divert" },
    { id: "FAC-R3-RAM", name: "Role 3 รามาฯ", name_en: "Role 3 Ramathibodi", x: 72, y: 30, type: "facility", role: "Role 3", status: "accept" },
    { id: "FAC-R3-CHU", name: "Role 3 จุฬาฯ", name_en: "Role 3 Chulalongkorn", x: 82, y: 60, type: "facility", role: "Role 3", status: "accept" },
    { id: "FAC-COE-PMK", name: "CoE พระมงกุฎฯ", name_en: "CoE Phramongkutklao", x: 85, y: 24, type: "facility", role: "CoE", status: "call" },
    { id: "UAV-1", name: "UAV-Hawk-1", x: 24, y: 28, type: "uav" },
    { id: "UAV-2", name: "UAV-Recon-2", x: 50, y: 42, type: "uav" },
  ],
  patient_markers: [
    { x: 27, y: 36, lvl: "p1" }, { x: 29, y: 39, lvl: "p2" }, { x: 30, y: 37, lvl: "p2" },
    { x: 32, y: 40, lvl: "p3" }, { x: 33, y: 38, lvl: "p3" }, { x: 31, y: 41, lvl: "p2" },
    { x: 41, y: 55, lvl: "p1" }, { x: 44, y: 56, lvl: "p1" }, { x: 43, y: 58, lvl: "p2" },
    { x: 40, y: 57, lvl: "p3" }, { x: 45, y: 54, lvl: "p3" }, { x: 42, y: 60, lvl: "black" },
  ],
  teams: [
    { id: "BOAT-01", code: "Boat Rescue 01", type: "boat", capability: "Water rescue", readiness: 100, status: "on_scene", site: "SITE-A", org: "RTN Marine" },
    { id: "BOAT-02", code: "Boat Rescue 02", type: "boat", capability: "Water rescue", readiness: 75, status: "en_route", site: "SITE-B", org: "RTN Marine" },
    { id: "MED-ALPHA", code: "Medical Alpha", type: "medical", capability: "MCI Triage", readiness: 100, status: "on_scene", site: "CCP-1", org: "RTA Medical" },
    { id: "MED-BRAVO", code: "Medical Bravo", type: "medical", capability: "Advanced trauma", readiness: 100, status: "en_route", site: "SITE-B", org: "Erawan EMS" },
    { id: "UAV-HAWK-1", code: "UAV Hawk 1", type: "drone", capability: "Recon / mapping", readiness: 75, status: "on_scene", site: "UAV-1", org: "RTAF UAV Sq" },
    { id: "UAV-RECON-2", code: "UAV Recon 2", type: "drone", capability: "Logistics drop", readiness: 100, status: "on_scene", site: "UAV-2", org: "RTAF UAV Sq" },
    { id: "LOG-BRAVO", code: "Logistics Bravo", type: "truck", capability: "Cold chain", readiness: 100, status: "en_route", site: "CCP-1", org: "ThaiPDR Logistics" },
    { id: "SAFETY-1", code: "Safety Officer 1", type: "safety", capability: "Hot zone monitor", readiness: 100, status: "on_scene", site: "SITE-A", org: "DDPM" },
    { id: "HEMS-01", code: "HEMS-01", type: "helicopter", capability: "Air medical", readiness: 50, status: "available", site: "LZ-1", org: "RTAF Medical" },
  ],
  facilities: [
    { id: "FAC-R2-SIR", name: "Role 2 Siriraj", name_th: "ศิริราชพยาบาล", role: "Role 2", beds: 12, beds_total: 40, icu: 0, icu_total: 8, or: 2, or_total: 4, blood: "low", oxygen: "ok", status: "divert", inbound: 4 },
    { id: "FAC-R3-RAM", name: "Role 3 Ramathibodi", name_th: "รามาธิบดี", role: "Role 3", beds: 28, beds_total: 60, icu: 6, icu_total: 12, or: 3, or_total: 6, blood: "ok", oxygen: "ok", status: "accept", inbound: 7 },
    { id: "FAC-R3-CHU", name: "Role 3 Chulalongkorn", name_th: "จุฬาลงกรณ์", role: "Role 3", beds: 22, beds_total: 55, icu: 4, icu_total: 10, or: 2, or_total: 5, blood: "ok", oxygen: "low", status: "accept", inbound: 5 },
    { id: "FAC-COE-PMK", name: "CoE Phramongkutklao", name_th: "พระมงกุฎเกล้า", role: "CoE", beds: 5, beds_total: 30, icu: 1, icu_total: 8, or: 1, or_total: 4, blood: "critical", oxygen: "ok", status: "call", inbound: 2 },
  ],
  events: [
    { time: "T+04:12", code: "FACILITY_DIVERSION", actor: "Role 2 Siriraj", target: "ICU saturation 100%", severity: "warning" },
    { time: "T+04:08", code: "SAFETY_GATE_VIOLATION", actor: "MED-BRAVO", target: "ENTER_HOT_ZONE without EOD_GATE", severity: "critical", flagged: true },
    { time: "T+04:05", code: "DISPATCH_ASSIGNED", actor: "Cmdr. Suriya", target: "MED-BRAVO → SITE-B", severity: "info" },
    { time: "T+04:01", code: "PATIENT_TRIAGED", actor: "MED-ALPHA", target: "PAT-2026-0847-022 P1", severity: "info" },
    { time: "T+03:58", code: "IAP_APPROVED", actor: "Cmdr. Suriya", target: "IAP v2.1 for OP-3", severity: "info" },
    { time: "T+03:55", code: "RESOURCE_REQUEST", actor: "MED-ALPHA", target: "12× O-neg blood, urgent", severity: "warning" },
    { time: "T+03:52", code: "PATIENT_TRANSPORT", actor: "BOAT-01", target: "PAT-021 → Role 3 Ramathibodi", severity: "info" },
    { time: "T+03:48", code: "TEAM_CHECK_IN", actor: "UAV-RECON-2", target: "On scene at SITE-A", severity: "info" },
    { time: "T+03:40", code: "ESCALATION", actor: "Bangkok EOC", target: "Local → Regional", severity: "warning" },
    { time: "T+03:32", code: "SAFETY_GATE_PASSED", actor: "Safety-1", target: "LZ_GATE @ LZ-1", severity: "info" },
  ],
  drill_injects: [
    { id: "INJ-001", t: "T+00:00", type: "communications", title: "METHANE Alert", target: "Commander Alpha", status: "acknowledged", expected: "Open incident, assign IAP team" },
    { id: "INJ-002", t: "T+00:30", type: "logistics", title: "Bridge Sirindhorn Closed", target: "Logistics Cell", status: "acknowledged", expected: "Reroute via Boat-2 corridor" },
    { id: "INJ-003", t: "T+01:00", type: "clinical", title: "P1 Surge — 12 new casualties", target: "Medical Cell + Field Teams", status: "pushed", expected: "Activate surge protocol, request additional Role 2" },
    { id: "INJ-004", t: "T+01:30", type: "hospital_surge", title: "Role 2 Siriraj reaches 100%", target: "Logistics + Medical", status: "pushed", expected: "Divert to Role 3, update COP" },
    { id: "INJ-005", t: "T+02:00", type: "communications", title: "Comms Degraded — Cell tower down", target: "All teams", status: "queued", expected: "Switch to TETRA, runner protocol" },
    { id: "INJ-006", t: "T+02:30", type: "safety", title: "HazMat Detection at SITE-B", target: "Safety Officer + Commander", status: "queued", expected: "Activate HAZMAT_GATE, evacuate warm zone" },
    { id: "INJ-007", t: "T+03:00", type: "public_information", title: "Media Inquiry — Casualty count", target: "PIO Cell", status: "queued", expected: "Release approved briefing" },
  ],
  safety_gates: [
    { code: "EOD_GATE", title: "ปลดวัตถุระเบิด", status: "passed", approved_by: "EOD-Lead-01", approved_at: "T+03:15", severity: "critical" },
    { code: "HAZMAT_GATE", title: "สารอันตราย", status: "pending", severity: "critical" },
    { code: "LZ_GATE", title: "ลานจอดอากาศยาน", status: "passed", approved_by: "Safety-1", approved_at: "T+03:32", severity: "critical" },
    { code: "HOSPITAL_GATE", title: "ขีดความสามารถของ รพ.", status: "failed", severity: "critical", note: "Role 2 รับ P1 ไม่ได้ ต้องจัดเส้นทางใหม่" },
    { code: "AUTHORITY_GATE", title: "อำนาจหลายหน่วย", status: "passed", approved_by: "JOC-Director", approved_at: "T+03:42", severity: "warning" },
    { code: "ROUTE_GATE", title: "เส้นทาง / สะพาน", status: "pending", severity: "warning", note: "ยืนยันสะพานสิรินธรปิด" },
  ],
  controllers: [
    { name: "พ.อ. อานันต์ วงศ์", role: "ผู้อำนวยการฝึก", status: "active" },
    { name: "พ.ต. ปรียา สุขสมะจิต", role: "ผู้ควบคุมอาวุโส", status: "active" },
    { name: "ร.อ. ศิริน กิตติ", role: "ผู้ควบคุมความปลอดภัย", status: "active" },
    { name: "ร.ท. วิรัช จันทร์ดี", role: "ผู้บันทึกข้อมูล", status: "active" },
  ],
  evaluators: [
    { name: "นพ. สุชาติ มงคล", role: "ผู้ประเมินด้านการแพทย์", scope: "หน่วยแพทย์", observations: 24 },
    { name: "พ.อ. พิชิต รัตน์", role: "ผู้ประเมินสั่งการ", scope: "ICP", observations: 18 },
    { name: "ร.อ. บุญ พรพรหม", role: "ผู้ประเมินความปลอดภัย", scope: "ทุกทีม", observations: 14 },
    { name: "ร.ท. วัสนา อินทร์พร", role: "ผู้ประเมินด้าน Logistics", scope: "หน่วย Logistics", observations: 11 },
  ],
  aar_findings: [
    { id: "FND-001", type: "safety_gate_violation", severity: "critical", title: "ละเมิด Safety Gate: เข้า HOT_ZONE โดยไม่ผ่าน EOD", summary: "ทีม MED-BRAVO เข้า hot zone ที่ SITE-B เวลา T+04:08 ก่อน EOD_GATE ผ่าน", cause: "การ brief IAP ไม่ได้ระบุว่า EOD gate เป็นด่านวิกฤต และ Safety Officer ไม่ได้อยู่ร่วม", recommendation: "บังคับให้มี Safety Officer ร่วมทุก brief · บล็อกการส่งผ่าน Authority Matrix", lms: { course: "INC-SAFETY-201", title: "ความปลอดภัยในเหตุ & สารอันตราย", roles: ["ภาคสนาม", "แพทย์"] } },
    { id: "FND-002", type: "hospital_mismatch", severity: "high", title: "จับคู่ รพ. ผิด: P1 ไป Role 2 ขณะเตียงเต็ม", summary: "ผู้ป่วย P1 3 รายถูกส่งไปศิริราช (Role 2) ขณะ ICU 100% ต้องส่งต่ออีกรอบ", cause: "สถานะ รพ. ล่าช้า 6 นาที และไม่มีสถานะรับ/เบี่ยงให้ภาคสนามเห็น", recommendation: "เบี่ยงอัตโนมัติเมื่อ ICU > 90% · ส่งสถานะ รพ. ไปภาคสนามภายใน 30 วินาที", lms: { course: "FAC-MATCH-110", title: "การจับคู่ขีดความสามารถของสถานพยาบาล", roles: ["แพทย์", "Logistics"] } },
    { id: "FND-003", type: "triage_accuracy_low", severity: "medium", title: "ความแม่นยำการคัดแยกต่ำกว่าเกณฑ์ ทีม 3B", summary: "ความแม่นยำอยู่ที่ 71% ต่ำกว่าเป้า 85% · P2 4 รายถูกจัดเป็น P3", cause: "ขั้นตอน MARCH ถูกข้าม 8 ราย · ไม่ตรวจซ้ำการหายใจ", recommendation: "ฝึกทบทวน START-SALT · แจกบัตรช่วยจำติดสายคล้อ", lms: { course: "MCI-TRIAGE-101", title: "การคัดแยก MCI START-SALT", roles: ["แพทย์", "ภาคสนาม"] } },
    { id: "FND-004", type: "logistics_stockout", severity: "high", title: "ขาดเลือด O-neg ที่ รพ. ศิริราช", summary: "ธนาคารเลือดเข้าสู่ระดับวิกฤตเมื่อ T+02:15 · ส่งเติมได้ T+03:55", cause: "ไม่มีการแจ้งเตือนล่วงหน้า · ขนส่ง cold chain ล่าช้าจากสะพานปิด", recommendation: "ตั้งเกณฑ์เตือน 6 ชม. ล่วงหน้า · เพิ่มขนส่งเลือดด้วยโดรน", lms: { course: "MED-LOG-202", title: "Logistics ทางการแพทย์ & Cold Chain", roles: ["Logistics"] } },
  ],
  registry: [
    { id: "UAV-RECON-2026-0011", type: "drone", name: "UAV Recon 2", status: "active", readiness: 100, owner: "RTAF UAV Sq", capabilities: ["recon","mapping","logistics"], updated: "T+03:48" },
    { id: "UAV-HAWK-2025-0007", type: "drone", name: "UAV Hawk 1", status: "active", readiness: 75, owner: "RTAF UAV Sq", capabilities: ["recon","thermal"], updated: "T+02:11" },
    { id: "BOAT-RTN-2026-0001", type: "vehicle", name: "Boat Rescue 01", status: "active", readiness: 100, owner: "RTN Marine", capabilities: ["water_rescue","transport"], updated: "T+04:05" },
    { id: "BOAT-RTN-2026-0002", type: "vehicle", name: "Boat Rescue 02", status: "active", readiness: 75, owner: "RTN Marine", capabilities: ["water_rescue"], updated: "T+03:58" },
    { id: "MED-ALPHA-001", type: "task_force", name: "Medical Alpha", status: "active", readiness: 100, owner: "RTA Medical", capabilities: ["MCI_triage","advanced_trauma"], updated: "T+04:01" },
    { id: "MED-BRAVO-002", type: "task_force", name: "Medical Bravo", status: "active", readiness: 100, owner: "Erawan EMS", capabilities: ["advanced_trauma","transport"], updated: "T+04:05" },
    { id: "FAC-ROLE3-BKK-2026-0001", type: "facility", name: "Role 3 Ramathibodi", status: "active", readiness: 75, owner: "MoPH", capabilities: ["Role3","trauma_center"], updated: "T+04:10" },
    { id: "FAC-ROLE2-BKK-2026-0002", type: "facility", name: "Role 2 Siriraj", status: "divert", readiness: 25, owner: "MoPH", capabilities: ["Role2","surgical"], updated: "T+04:12" },
    { id: "PAT-SIM-FLD-A-001", type: "patient", name: "Sim Patient A-001", status: "triaged", readiness: 50, owner: "Drill Cell", capabilities: ["P2_yellow"], updated: "T+01:32" },
    { id: "STD-TRIAGE-START-2026-01", type: "standard", name: "START-SALT Triage Protocol", status: "active", readiness: 100, owner: "MoPH", capabilities: ["measurement","training"], updated: "T-30d" },
  ],
  scenario_templates: [
    { id: "TPL-FLOOD-MCI", title: "น้ำท่วม + MCI + Hospital Surge", type: "flood_mci", casualties: "200-300", duration: "4-6 ชม.", risk: "สะพานปิด · Role 2 เต็ม" },
    { id: "TPL-EXPLOSION-URBAN", title: "เหตุระเบิด อาคารสูงกลางเมือง", type: "explosion", casualties: "60-120", duration: "3-5 ชม.", risk: "ระเบิดซ้อน · EOD gate" },
    { id: "TPL-CBN-HAZMAT", title: "CBN / HazMat โรงงานอุตสาหกรรม", type: "cbn_hazmat", casualties: "40-80", duration: "6-8 ชม.", risk: "ชำระล้าง · hot zone ขยาย" },
    { id: "TPL-MEDEVAC-REMOTE", title: "MEDEVAC พื้นที่ทุรกันดาร", type: "medevac", casualties: "8-20", duration: "2-3 ชม.", risk: "อากาศ เชื้อเพลิง สื่อสาร" },
    { id: "TPL-HOSPITAL-SURGE", title: "Hospital Surge / ส่งต่อระหว่าง รพ.", type: "hospital_surge", casualties: "80-150", duration: "4-8 ชม.", risk: "ICU เต็ม · เลือด" },
  ],
  casualty_archetypes: [
    { id: "ARC-P1-BLEED", title: "P1 — เลือดออกมาก", triage: "P1", facility: "Role 3", cues: "เลือดพุ่ง, ชีพจรเบา, GCS 14", count: 12 },
    { id: "ARC-AIRWAY", title: "ทางเดินหายใจอุดตัน", triage: "P1", facility: "Role 2", cues: "Stridor, เขียว, ใช้กล้ามเนื้อช่วย", count: 8 },
    { id: "ARC-DROWN", title: "จมน้ำ / ขาดออกซิเจน", triage: "P1", facility: "Role 3", cues: "หมดสติ, SpO2 < 88, ฟองชมพูสีชมพู", count: 6 },
    { id: "ARC-ELDER-BED", title: "ผู้สูงอายุติดเตียง", triage: "P2", facility: "Role 1/2", cues: "อุณหภูมิต่ำ, ขาดน้ำ, เคลื่อนไหวไม่ได้", count: 24 },
    { id: "ARC-WALKING", title: "บาดเล็กน้อย (Walking)", triage: "P3", facility: "CCP", cues: "เดินได้, บาดถลอกเล็ก, ตื่นตระหนก", count: 47 },
  ],
  evaluation_metrics: [
    { code: "TRIAGE_ACC", title: "ความแม่นยำการคัดแยก", value: 79, target: 85, unit: "%", tone: "warn" },
    { code: "P1_FIRST_CONTACT", title: "เวลาถึง P1 รายแรก", value: "11:24", target: "≤ 10:00", unit: "", tone: "warn" },
    { code: "SAFETY_VIOLATIONS", title: "ละเมิด Safety Gate", value: 3, target: 0, unit: "", tone: "critical" },
    { code: "RECORD_COMPLETE", title: "ความครบถ้วนของบันทึก", value: 92, target: 95, unit: "%", tone: "warn" },
    { code: "IAP_CYCLE", title: "รอบสร้าง IAP", value: "18:42", target: "≤ 20:00", unit: "", tone: "ok" },
    { code: "COP_COMPLETE", title: "COP ครบถ้วน", value: 87, target: 90, unit: "%", tone: "warn" },
  ],
  team_performance: [
    { code: "ทีม 1A — เรือกู้ภัย", score: 4.2, status: "good", findings: 2 },
    { code: "ทีม 2A — Medical Alpha", score: 3.8, status: "good", findings: 3 },
    { code: "ทีม 2B — Medical Bravo", score: 2.4, status: "issue", findings: 5 },
    { code: "ทีม 3A — UAV Recon", score: 4.6, status: "excellent", findings: 1 },
    { code: "ทีม 3B — คัดแยกสนาม", score: 2.8, status: "issue", findings: 4 },
    { code: "ทีม 4A — ส่งกำลัง", score: 3.5, status: "good", findings: 2 },
  ],
  field_inbox: [
    { id: "MSG-001", from: "ห้องควบคุม", time: "T+01:32", title: "P1 SURGE — ผู้ป่วยใหม่ 12 รายเข้า", body: "เปิดระบบ Surge MCI · เตรียมจุดคัดแยกรองรับ", severity: "critical", ack: false },
    { id: "MSG-002", from: "พ.อ. สุริยะ", time: "T+01:28", title: "ย้ายไป CCP-1", body: "MED-ALPHA ปรับตำแหน่ง ไปจุดรวมผู้ป่วย 1", severity: "warning", ack: true },
    { id: "MSG-003", from: "Safety-1", time: "T+01:15", title: "ผ่านด่าน LZ แล้ว", body: "LZ-1 พร้อมรับ HEMS ลงจอด — ลานพระอาทิตย์", severity: "info", ack: true },
  ],
};
